[package]
name                   = "meridian-local"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
async-trait.workspace = true
meridian-credential-store.workspace = true
meridian-platform.workspace         = true
meridian-sync-protocol.workspace    = true
meridian-types.workspace            = true
tokio.workspace = true

[dev-dependencies]
meridian-steam.workspace = true

[lints]
workspace = true
