[package]
name                   = "meridian-credential-store"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true

[dependencies]
async-trait.workspace = true
secrecy              = { features = [ "serde" ], version = "0.10.3" }
serde.workspace      = true
serde_json.workspace = true
thiserror.workspace  = true
tokio.workspace = true

[lints]
workspace = true
